import Image from 'next/image';
import Head from 'next/head';

const Termsofuse = () => {
	return (
		<div>
			<Head>
				<title>AnyWorkX | Terms of Use</title>
				<meta name='description' content='Generated by create next app' />
			</Head>
			<div className='container relative'>
				<div className='absolute hidden lg:block left-0 top-[100px]'>
					<Image
						src='/images/circle.png'
						alt='circle point'
						width={'110px'}
						height={'180px'}
					/>
				</div>
				<div className='absolute hidden lg:block right-0 bottom-0'>
					<Image
						src='/images/circle2.png'
						alt='circle point'
						width={'110px'}
						height={'180px'}
					/>
				</div>
				<div className='lg:mt-[180px] mt-[145px] mb-[65px] lg:mb-[100px] px-[33px] lg:px-[234px]'>
					<h2 className='mb-[24px] text-primary capitalize text-center lg:mb-[38px]'>
						Terms And Conditions Of Use
					</h2>
					<h3 className='text-2xl text-left'>Introduction</h3>
					<p className='mb-[15px] xl:mb-[25px]'>
						These terms and conditions apply between you, the User of this
						Website (including any sub-domains, unless expressly excluded by
						their own terms and conditions), and ANYWORKX, the owner and
						operator of this Website. Please read these terms and conditions
						carefully, as they affect your legal rights. Your agreement to
						comply with and be bound by these terms and conditions is deemed to
						occur upon your first use of the Website. If you do not agree to be
						bound by these terms and conditions, you should stop using the
						Website immediately.
						<br />
					</p>
					<p className='mb-[15px] xl:mb-[25px]'>
						{' '}
						In these terms and conditions,{' '}
						<span className='font-bold'>Customer</span> or{' '}
						<span className='font-bold'>Customers</span> means any third party that
						accesses the Website and is not either (i) employed by ANYWORKX and
						acting in the course of their employment or (ii) engaged as a
						consultant or otherwise providing services to ANYWORKX and accessing
						the Website in connection with the provision of such services.{' '}
						<br />
					</p>
					<p>
						You must be at least 18 years of age to use this Website. By using
						the Website and agreeing to these terms and conditions, you
						represent and warrant that you are at least 18 years of age.
					</p>
					<h3 className='text-2xl mt-7 text-left'>
						Intellectual property and acceptable use
					</h3>
					<p>
						<span className='mr-3'>1.</span> All Content included on the
						Website, unless uploaded by Customers, is the property of ANYWORKX, our
						affiliates or other relevant third parties. In these terms and
						conditions, Content means any text, graphics, images, audio, video,
						software, data compilations, page layout, underlying code and
						software and any other form of information capable of being stored
						in a computer that appears on or forms part of this Website,
						including any such content uploaded by Customers. By continuing to use
						the Website you acknowledge that such Content is protected by
						copyright, trademarks, database rights and other intellectual
						property rights. Nothing on this site shall be construed as
						granting, by implication, estoppel, or otherwise, any license or
						right to use any trademark, logo or service mark displayed on the
						site without the owner&apos;s prior written permission. <br />
					</p>
					<p>
						<span className='mr-3'>2.</span> You may, for your own personal,
						non-commercial use only, do the following: <br />
						<span className='mr-3'>3.</span> You must not otherwise reproduce,
						modify, copy, distribute or use for commercial purposes any Content
						without the written permission of ANYWORKX.
					</p>
					<h3 className='text-2xl mt-7 text-left'>Prohibited use</h3>
					<p>
						<span className='mr-3'>4.</span> You may not use the Website for any
						of the following purposes: <br /> a. in any way which causes, or may
						cause, damage to the Website or interferes with any other
						person&apos;s use or enjoyment of the Website; <br /> b. in any way
						which is harmful, unlawful, illegal, abusive, harassing, threatening
						or otherwise objectionable or in breach of any applicable law,
						regulation, governmental order; <br /> c. making, transmitting or
						storing electronic copies of Content protected by copyright without
						the permission of the owner.
					</p>
					<h3 className='text-2xl mt-7 text-left'>
						Privacy Policy and Cookies Policy
					</h3>
					<p>
						<span className='mr-3'>5.</span> Use of the Website is also governed
						by our Privacy Policy and Cookies Policy, which are incorporated
						into these terms and conditions by this reference. To view the
						Privacy Policy and Cookies Policy, please click on the following:
						and .
					</p>
					<h3 className='text-2xl mt-7 text-left'>
						Availability of the Website and disclaimers
					</h3>
					<p>
						<span className='mr-3'>6.</span> Any online facilities, tools,
						services or information that ANYWORKX makes available through the
						Website (the Service) is provided &quot;as is&quot; and on an
						&quot;as available&quot; basis. We give no warranty that the Service
						will be free of defects and/or faults. To the maximum extent
						permitted by the law, we provide no warranties (express or implied)
						of fitness for a particular purpose, accuracy of information,
						compatibility and satisfactory quality. ANYWORKX is under no
						obligation to update information on the Website. <br />
						<span className='mr-3'>7.</span> Whilst ANYWORKX uses reasonable
						endeavours to ensure that the Website is secure and free of errors,
						viruses and other malware, we give no warranty or guaranty in that
						regard and all Customers take responsibility for their own security,
						that of their personal details and their computers. <br />
						<span className='mr-3'>8.</span> ANYWORKX accepts no liability for
						any disruption or non-availability of the Website. <br />
						<span className='mr-3'>9.</span> ANYWORKX reserves the right to
						alter, suspend or discontinue any part (or the whole of) the Website
						including, but not limited to, any products and/or services
						available. These terms and conditions shall continue to apply to any
						modified version of the Website unless it is expressly stated
						otherwise.
					</p>
					<h3 className='text-2xl mt-7 text-left'>Limitation of liability</h3>
					<p>
						<span className='mr-3'>10.</span> Nothing in these terms and
						conditions will: (a) limit or exclude our or your liability for
						death or personal injury resulting from our or your negligence, as
						applicable; (b) limit or exclude our or your liability for fraud or
						fraudulent misrepresentation; or (c) limit or exclude any of our or
						your liabilities in any way that is not permitted under applicable
						law. <br />
						<span className='mr-3'>11.</span> We will not be liable to you in
						respect of any losses arising out of events beyond our reasonable
						control. <br />
						<span className='mr-3'>12.</span> To the maximum extent permitted by
						law, ANYWORKX accepts no liability for any of the following: <br />{' '}
						a. any business losses, such as loss of profits, income, revenue,
						anticipated savings, business, contracts, goodwill or commercial
						opportunities; <br /> b. loss or corruption of any data, database or
						software; <br /> c. any special, indirect or consequential loss or
						damage.
					</p>

					<h3 className='text-2xl mt-7 text-left'>General</h3>
					<p>
						<span className='mr-3'>13.</span> You may not transfer any of your
						rights under these terms and conditions to any other person. We may
						transfer our rights under these terms and conditions where we
						reasonably believe your rights will not be affected. <br />
						<span className='mr-3'>14.</span> These terms and conditions may be
						varied by us from time to time. Such revised terms will apply to the
						Website from the date of publication. Customers should check the terms
						and conditions regularly to ensure familiarity with the then current
						version. <br />
						<span className='mr-3'>15.</span> These terms and conditions
						together with the Privacy Policy and Cookies Policy contain the
						whole agreement between the parties relating to its subject matter
						and supersede all prior discussions, arrangements or agreements that
						might have taken place in relation to the terms and conditions.{' '}
						<br />
						<span className='mr-3'>16.</span> The Contracts (Rights of Third
						Parties) Act 1999 shall not apply to these terms and conditions and
						no third party will have any right to enforce or rely on any
						provision of these terms and conditions. <br />{' '}
						<span className='mr-3'>17.</span> If any court or competent
						authority finds that any provision of these terms and conditions (or
						part of any provision) is invalid, illegal or unenforceable, that
						provision or part-provision will, to the extent required, be deemed
						to be deleted, and the validity and enforceability of the other
						provisions of these terms and conditions will not be affected.{' '}
						<br />
						<span className='mr-3'>18.</span> Unless otherwise agreed, no delay,
						act or omission by a party in exercising any right or remedy will be
						deemed a waiver of that, or any other, right or remedy. <br />
						<span className='mr-3'>19.</span> This Agreement shall be governed
						by and interpreted according to the law of Nigeria and all disputes
						arising under the Agreement (including non-contractual disputes or
						claims) shall be subject to the exclusive jurisdiction of the
						Nigerian courts.
					</p>

					<h3 className='text-2xl mt-7 text-left'>ANYWORKX details</h3>
					<p>
						<span className='mr-3'>20.</span> ANYWORKX is a company incorporated
						in whose registered address is 2nd floor, Awolowo House, Obafemi
						Awolowo way, Ikeja., P.O.Box 5013, Ikeja. Lagos-State Nigeria,
						LAGOS, and it operates the Website www.anyworkx-ng.com.
					</p>

					<p>
						You can contact ANYWORKX by email on{' '}
						<span className='text-purple-500'>
							<a href='mailto:support@anyworkx.com'>support@anyworkx.com.</a>
						</span>
					</p>
				</div>
			</div>
		</div>
	);
};

export default Termsofuse;
