import React, { useState } from 'react';
import { useRouter } from 'next/router';
import type { NextPage } from 'next';
import Head from 'next/head';
import Accordion from '../../components/faq/Accordion';
import Button from '../../components/UI/Button';
import Image from 'next/image';
import Link from 'next/link';

const Faq: NextPage = () => {
	const accordionData = [
		{
			id: 1,
			title: 'What kind of service does AnyworkX provide?',
			content: `AnyworkX provides a reliable vendor to do all kinds of daily services requested by customers. We have professional vendors ranging from make-up artists to plumbers, food vendors, and many others.`,
		},
		{
			id: 2,
			title: 'Is there a fixed amount for service rendered?',
			content: `No, there is no fixed amount. The customer and the vendor negotiate the service charges and agree on the amount to be paid for the service.
`,
		},
		{
			id: 3,
			title: 'As a Vendor, do I get paid before delivering service or after?',
			content: `As an vendor, customers make a substantial initial payment (known as a call-out fee) after you’ve struck a bargain. You get the final payment after the service must have been completed.`,
		},
		{
			id: 4,
			title: 'Can I change vendors at any time?',
			content: `Yes, you can change vendors based on your preference, but this can only be done if you have not reached an agreement with the vendor. `,
		},
		{
			id: 5,
			title: 'Is payment secure?',
			content: `Yes, we have a payment method that is safe, secure, and efficient for both customer and vendor transactions.`,
		},
		{
			id: 6,
			title: 'Are my details safe with AnyworkX?',
			content: `One of our core values is confidentiality. We would never divulge either customer's or vendor's details to a third party.`,
		},
		{
			id: 7,
			title: 'Is my location visible on the app?',
			content: `As soon as you turn on your google location on your device, we can pair you with the closest vendor in your location.`,
		},
	];

	const [activeIndex, setActiveIndex] = useState(0);
	const router = useRouter();
	const displayPageLayout = router.query.hideLayout === 'true' ? false : true;

	return (
		<div>
			<Head>
				<title>AnyworkX | FAQs</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='shortcut icon' href='images/favicon.jpg' />
			</Head>
			<main className='xl:mt-[144px] mt-[112px]'>
				<div className=' accordions py-[30px]'>
					<div className='container relative lg:px-[112px] px-[33px]'>
						<div className='absolute hidden lg:block left-0 top-[70px] z-[-1]'>
							<Image
								src='/images/circle.png'
								alt='circle'
								width={110}
								height={180}
							/>
						</div>
						<div className='absolute hidden lg:block bottom-[20px] right-0 z-[-1]'>
							<Image
								src='/images/circle2.png'
								alt='circle'
								width={110}
								height={180}
							/>
						</div>
						<div className=' md:w-[64%] m-[auto] w-[100%]'>
							<div className='heading text-center'>
								<h3 className='text-font-03 font-semibold'>
									We have answers to all your inquiries
								</h3>
								<p className='text-grey mt-[10px] text-base'>
									Here are some of the frequently asked questions.
								</p>
							</div>
							<div className='accordion  my-[40px]'>
								<>
									{accordionData.map(({ title, content, id }) => (
										<Accordion
											key={id}
											title={title}
											index={id}
											activeIndex={activeIndex}
											setActiveIndex={setActiveIndex}
											content={content}
										/>
									))}
								</>
							</div>
						</div>
					</div>
				</div>

				{displayPageLayout && (
					<div className='container lg:px-[112px] px-[33px]'>
						<div className='still text-center bg-cyan rounded-lg mt-[30px] mb-[100px] py-[30px] px-[15px]'>
							<h2 className='text-font-01 font-bold text-lg'>
								Your Questions Are Not Here?
							</h2>
							<p className='text-grey my-2 text-sm'>
								Feel free to ask our friendly team directly
							</p>
							<Link href='/contact-us'>
								<a>
									<Button styles='bg-primary m-[auto]' content='Get in touch' />
								</a>
							</Link>
						</div>
					</div>
				)}
			</main>
		</div>
	);
};

export default Faq;
