import type { NextPage } from 'next';
import Head from 'next/head';
import ServiceCard from '../components/services/ServiceCard';
import Header from '../components/UI/Header';
import LoveToHear from '../components/contact/LoveToHear';
import Image from 'next/image';


const About: NextPage = () => {

  
    return (
        <div>
            <Head>
                <title>Anyworks | Services</title>
                <meta name='description' content='Generated by create next app' />
                <link rel="shortcut icon" href="svgs/logo.svg" />
            </Head>
            <Header />
            <main className=' pt-[80px]'>
            <div className=" py-[30px] about-intro">
                    <div className="container about-intro-content text-center w-[75%] md:w-full mx-[auto]  ">
                        <h2 className="text-[#7e00c4] font-semibold text-lg">About Us</h2>
                        <p className='text-font-01 py-2 font-bold'>We do things differently...</p>
                        <p className="text-xs text-font-01">
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Velit at donec mi diam leo aliquam non sagittis. Sapien auctor diam elementum faucibus condimentum quam eget. Odio a, elementum laoreet sed.  Lorem ipsum dolor sit amet, 
                        </p>

                        <div className="mission-vision mt-[50px] flex flex-col gap-y-4">
                        <div className="mission">
                        <h2 className="text-[#7e00c4] font-semibold text-base">Mission</h2>
                        <p className="text-xs text-font-01">
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Velit at donec mi diam leo aliquam non sagittis. Sapien auctor diam elementum faucibus condimentum quam eget. Odio a, elementum laoreet sed.  Lorem ipsum dolor sit amet, 
                        </p>
                        </div>
                        <div className="vision">
                        <h2 className="text-[#7e00c4] font-semibold text-base">Vision</h2>
                        <p className="text-xs text-font-01">
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Velit at donec mi diam leo aliquam non sagittis. Sapien auctor diam elementum faucibus condimentum quam eget. Odio a, elementum laoreet sed.  Lorem ipsum dolor sit amet, 
                        </p>
                        </div>

                        </div>
                    </div>
                </div>
                <div className="bg-white py-[80px] contact">
                <LoveToHear/>

                </div>

            </main >
        </div >
    );
};

export default About;
