import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../components/UI/Header'
import Accordion from '../components/faq/Accordion'
import Button from '../components/UI/Button'

const Faq: NextPage = () => {
  const accordionData = [
    {
      title: 'What does Yawo Mean?',
      content: `Yawo is a Yoruba word meaning “to borrow money”. It’s a platform which provides capital for small businesses.`,
    },
    {
      title: 'Who can borrow from Yawo?',
      content: `Traders and small businesses.`,
    },
    {
      title: 'How much I can get from Yawo?',
      content: `All customers get an initial loan of N25,000 and this can be gradually increased after regular repayments have been made.`,
    },
    {
      title: 'How do I repay my loan? ',
      content: `Repayment is made daily to Yawo partner agents until the end of the Loan period.`,
    },
    {
      title: 'How many times can I get a loan from Yawo?',
      content: `As many times as your loan is approved, provided earlier loans have been fully repaid.`,
    },
    {
      title: 'How do I find Yawo Partner Agents?',
      content: `Please contact us via phone in order to be connected with a Yawo Partner Agent.`,
    },
    {
      title: 'What are other advantages of Yawo?',
      content: `Yawo helps you save 5% of your daily repayment. This will be paid to you at the end of the loan period. Terms and conditions apply.`,
    },
  ]

  return (
    <div>
      <Head>
        <title>Anyworks | FAQs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="shortcut icon" href="svgs/logo.svg" />
      </Head>
      <Header />
      <main className=" pt-[80px]">
        <div className=" accordions py-[30px]">
          <div className="container">
            <div className=" w-[70%] m-[auto] md:w-[100%]">
              <div className="heading text-center">
                <h2 className="text-font-03 font-semibold text-xl">Frequently asked questions</h2>
                <p className="text-grey mt-[20px] text-base">
                  Everything you need to know about the product and billing.
                </p>
              </div>
              <div className="accordion my-[40px]">
                {accordionData.map(({ title, content }) => (
                  <Accordion key={title} title={title} content={content} />
                ))}
              </div>
            </div>
          </div>
        </div>

        <div className="container">
          <div className="still text-center bg-cyan rounded-lg my-[30px] py-[30px] px-[15px]">
            <h2 className="text-font-01 font-bold text-lg">Still have questions?</h2>
            <p className="text-grey my-2 text-sm">
              Can’t find the answer you’re looking for? Please chat to our friendly team.
            </p>
            <Button styles="bg-primary " content="Get in touch" />
          </div>
        </div>
      </main>
    </div>
  )
}

export default Faq
