import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../components/UI/Header'
import Accordion from '../components/faq/Accordion'
import Button from '../components/UI/Button'

const Faq: NextPage = () => {
  const accordionData = [
    {
      title: 'Is there a free trial available?',
      content: `Yes, you can try us for free for 30 days. If you want, we’ll provide you with a free, personalized 30-minute onboarding call to get you up and running as soon as possible.`,
    },
    {
      title: 'Can I change my plan later?',
      content: `No`,
    },
    {
      title: 'What is your cancellation policy?',
      content: `Yes, you can try us for free for 30 days. If you want, we’ll provide you with a free, personalized 30-minute onboarding call to get you up and running as soon as possible.`,
    },
    {
      title: 'Can other info be added to an invoice?',
      content: `Yes, you can try us for free for 30 days. If you want, we’ll provide you with a free, personalized 30-minute onboarding call to get you up and running as soon as possible.`,
    },
    {
      title: 'How does billing work?',
      content: `As many times as your`,
    },
    {
      title: 'How do I change my account email?',
      content: `Please contact us via phone in order to be connected`,
    },
  ]

  return (
    <div>
      <Head>
        <title>Anyworks | FAQs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="shortcut icon" href="svgs/logo.svg" />
      </Head>
      <Header />
      <main className=" pt-[80px]">
        <div className=" accordions py-[30px]">
          <div className="container">
            <div className=" w-[70%] m-[auto] md:w-[100%]">
              <div className="heading text-center">
                <h2 className="text-font-03 font-semibold text-xl">Frequently asked questions</h2>
                <p className="text-grey mt-[20px] text-base">
                  Everything you need to know about the product and billing.
                </p>
              </div>
              <div className="accordion my-[40px]">
                {accordionData.map(({ title, content }) => (
                  <Accordion key={title} title={title} content={content} />
                ))}
              </div>
            </div>
          </div>
        </div>

        <div className="container">
          <div className="still text-center bg-cyan rounded-lg my-[30px] py-[30px] px-[15px]">
            <h2 className="text-font-01 font-bold text-lg">Still have questions?</h2>
            <p className="text-grey my-2 text-sm">
              Can’t find the answer you’re looking for? Please chat to our friendly team.
            </p>
            <Button styles="bg-primary " content="Get in touch" />
          </div>
        </div>
      </main>
    </div>
  )
}

export default Faq
