import type { NextPage } from 'next';
import Head from 'next/head';
import HomepageHero from '../components/section/HomepageHero';
// import Header from '../components/UI/Header';
import styles from '../styles/Home.module.css';
import ServiceSection from '../components/section/Service';
import LearnMore from '../components/section/LearnMore';
import Howitworks from '../components/section/Howitworks';
import Whyanyworks from '../components/section/Whyanyworks';
import Link from 'next/link';

const Home: NextPage = () => {
	return (
		<div className={styles.homeBg}>
			<Head>
				<title>Anyworks | Website</title>
				<meta name='description' content='Generated by create next app' />
				{/* <link rel="icon" href="/favicon.ico" /> */}
			</Head>
			{/* <Header/> */}
			<main className='min-h-screen'>
				<HomepageHero />
				<div className='mt-[50px] mb-[90px] lg:mb-[200px] '>
					<ServiceSection />
				</div>
				<div className='mb-[80px] lg:mb-[120px]'>
					<LearnMore />
				</div>
				<Howitworks />
				<div className='container px-[33px] lg:px-[169px] py-[36px] lg:pt-[120px] lg:pb-[200px]'>
					<Whyanyworks />
				</div>
			</main>
		</div>
	);
};

export default Home;
