import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import HomepageHero from '../components/section/HomepageHero';
import Button from '../components/UI/Button';
import styles from '../styles/Home.module.css';
import ServiceSection from '../components/section/Service';
import LearnMore from '../components/section/LearnMore';
import Howitworks from '../components/section/Howitworks';
import Whyanyworks from '../components/section/Whyanyworks';

const Home: NextPage = () => {
	return (
		<div className={styles.homeBg}>
			<Head>
				<title>Anyworks | Website</title>
				<meta name='description' content='Generated by create next app' />
				{/* <link rel="icon" href="/favicon.ico" /> */}
			</Head>
			<div className='container'>
				<header className='px-[112px] py-[22px] flex items-center justify-between'>
					<div className='relative h-[52px] w-[159px]'>
						<Image
							src={'/images/anyworks-logo.png'}
							alt='anyworks logo'
							layout='fill'
						/>
					</div>
					<nav>
						<ul className='flex gap-x-[64px]'>
							<li className='navText'>Services</li>
							<li className='navText'>FAQs</li>
						</ul>
					</nav>
					<Button styles='bg-[#7E00C4]' content='join the waitlist' />
				</header>
			</div>
			<main className='min-h-screen'>
				<HomepageHero />
				<div className='mt-[50px] mb-[200px] '>
					<ServiceSection />
				</div>
				<div className='mb-[120px]'>
					<LearnMore />
				</div>
				<Howitworks />
				<div className='container px-[169px] pt-[120px] pb-[200px]'>
					<Whyanyworks />
				</div>
			</main>
		</div>
	);
};

export default Home;
