import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import HomepageHero from '../components/section/HomepageHero';
import Button from '../components/UI/Button';
import styles from '../styles/Home.module.css';
import ServiceSection from '../components/section/Service';
import LearnMore from '../components/section/LearnMore';
import Howitworks from '../components/section/Howitworks';
import Whyanyworks from '../components/section/Whyanyworks';
import Link from 'next/link';
import Header from '../components/Header';
import Footer from '../components/Footer';

const Home: NextPage = () => {
	return (
		<div className={styles.homeBg}>
			<Head>
				<title>Anyworks | Website</title>
				<meta name='description' content='Generated by create next app' />
				{/* <link rel="icon" href="/favicon.ico" /> */}
			</Head>
			<main className='min-h-screen'>
				<HomepageHero />
				<div className='mt-[50px] mb-[200px] '>
					<ServiceSection />
				</div>
				<div className='mb-[120px]'>
					<LearnMore />
				</div>
				<Howitworks />
				<div className='container px-[169px] pt-[120px] pb-[200px]'>
					<Whyanyworks />
				</div>
			</main>
		</div>
	);
};

export default Home;
