import type { NextPage } from 'next';
import Head from 'next/head';
import ServiceCard from '../components/services/ServiceCard';
import Header from '../components/UI/Header';

const Services: NextPage = () => {

    const allServices = [
        {
            title: 'Quick Errands',
        },
        {
            title: 'Quick Errands',
        },
        {
            title: 'Electrician',
        },
        {
            title: 'Hair Stylist',
        },
        {
            title: 'Laundry',
        },
        {
            title: 'Food',
        }
    ]
    return (
        <div>
            <Head>
                <title>Anyworks | Services</title>
                <meta name='description' content='Generated by create next app' />
                {/* <link rel="icon" href="/favicon.ico" /> */}
            </Head>
            <Header />
            <main className=' pt-[120px]'>
                <div className=" py-[20px] services-intro">
                    <div className="container service-intro-content text-center w-[60%] mx-[auto]  ">
                        <h2 className="text-[#7e00c4] font-semibold text-lg">Services</h2>
                        <p className='text-font-01 py-2 font-bold'>Lorem ipsum dolor sit amet consectetur</p>
                        <p className="text-xs text-font-02">
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Velit at donec mi diam leo aliquam non sagittis. Sapien auctor diam
                        </p>
                    </div>
                </div>
                <div className="services bg-cyan">
                    <div className="container services-content py-9 relative grid gap-4" style={{
                        gridTemplateColumns: 'repeat(auto-fill, minmax(300px, 1fr))'
                    }}>
                        {
                            allServices.map((service) => {
                                return (
                                    <div key={service.title}>
                                        <p>{service.title}</p>
                                    </div>
                                )
                            })
                        }
                    </div>
                </div>
            </main >
        </div >
    );
};

export default Services;
