import type { NextPage } from 'next';
import Head from 'next/head';
import ServiceCard from '../components/services/ServiceCard';
import Header from '../components/UI/Header';
import Howitworks from '../components/section/Howitworks';


const Services: NextPage = () => {

    const allServices = [
        {
            title: 'Quick Errands',
            image: '/images/services/service1.png'
        },
        {
            title: 'Plumber',
            image: '/images/services/service2.png'

        },
        {
            title: 'Electrician',
            image: '/images/services/service3.png'

        },
        {
            title: 'Hair Stylist',
            image: '/images/services/service4.png'

        },
        {
            title: 'Laundry',
            image: '/images/services/service5.png'

        },
        {
            title: 'Food',
            image: '/images/services/service6.png'

        }
    ]
    return (
        <div>
            <Head>
                <title>Anyworks | Services</title>
                <meta name='description' content='Generated by create next app' />
                <link rel="shortcut icon" href="svgs/logo.svg" />
            </Head>
            <Header />
            <main className=' pt-[80px]'>
                <div className=" py-[30px] services-intro">
                    <div className="container service-intro-content text-center w-[75%] md:w-full mx-[auto]  ">
                        <h2 className="text-primary font-semibold text-lg">Services</h2>
                        <p className='text-font-01 py-2 font-bold'>Lorem ipsum dolor sit amet consectetur</p>
                        <p className="text-xs text-font-02">
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Velit at donec mi diam leo aliquam non sagittis. Sapien auctor diam
                        </p>
                    </div>
                </div>
                <div className="services bg-cyan">
                    <div className="container services-content py-9 relative grid gap-[40px]" style={{
                        gridTemplateColumns: 'repeat(auto-fill, minmax(214px, 1fr))'
                    }}>
                        <>
                            {
                                allServices.map((service) => {
                                    return (
                                        <div key={service.title}>
                                            <ServiceCard service={service} />
                                        </div>
                                    )
                                })
                            }
                        </>

                    </div>
                </div>
                <Howitworks />

            </main >
        </div >
    );
};

export default Services;
